# Code generated by ChatGPT
#このコードはChatGPTが書いてるよ

from app import app, db, User

with app.app_context():
    # もし school_id カラムがまだなければ追加
    try:
        db.session.execute(db.text(
            "ALTER TABLE user ADD COLUMN school_id VARCHAR(100) DEFAULT 'hasaki3sousuke'"
        ))
        db.session.commit()
        print("✅ school_id カラムを追加しました")
    except Exception as e:
        print("⚠️ 既に school_id カラムが存在するか、別のエラー:", e)

    # 既存ユーザーに school_id を設定
    users = User.query.all()
    for u in users:
        if not getattr(u, "school_id", None):
            u.school_id = "hasaki3sousuke"
    db.session.commit()
    print("✅ 既存ユーザーに school_id を付与しました")
