# Code generated by ChatGPT
#このコードはChatGPTが書いてるよ

import sqlite3
import shutil

shutil.copyfile('instance/database.db', 'instance/database_backup.db')
print("バックアップを作成しました: database_backup.db")

conn = sqlite3.connect(r'instance/database.db')
c = conn.cursor()


c.execute("SELECT * FROM user;")
print("ユーザー一覧:", c.fetchall())


c.execute("DELETE FROM user WHERE username='admin';")
conn.commit()


c.execute("SELECT * FROM user;")
print("削除後のユーザー一覧:", c.fetchall())

conn.close()
print("admin アカウントを削除しました")
