# Code generated by ChatGPT
#このコードはChatGPTが書いてるよ

import sqlite3

# データベースに接続
conn = sqlite3.connect(r'instance/database.db')
c = conn.cursor()

# 1. データベース内の全テーブル名を取得
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = c.fetchall()

print("テーブル一覧と内容:")
for table_name_tuple in tables:
    table_name = table_name_tuple[0]
    print(f"\n=== {table_name} ===")
    
    # テーブル内の全データを取得
    try:
        c.execute(f"SELECT * FROM {table_name};")
        rows = c.fetchall()
        
        # カラム名を取得
        c.execute(f"PRAGMA table_info({table_name});")
        columns = [col[1] for col in c.fetchall()]
        
        # 見やすく表示
        print(" | ".join(columns))
        for row in rows:
            print(" | ".join(str(r) for r in row))
    except sqlite3.Error as e:
        print(f"エラー: {e}")

conn.close()
