# Code generated by ChatGPT
#このコードはChatGPTが書いてるよ

import sqlite3

# データベースに接続
conn = sqlite3.connect(r'instance/database.db')
c = conn.cursor()

# user テーブルの id, username, password を取得
c.execute("SELECT id, username, password FROM user;")
rows = c.fetchall()

print("=== user ===")
print("id | username | password")
for row in rows:
    print(f"{row[0]} | {row[1]} | {row[2]}")

conn.close()
